# Generated by Django 5.2.12 on 2026-03-10 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('base_equipment', 'Base Equipment'), ('generator', 'Generator'), ('hvac', 'HVAC System'), ('water_system', 'Water System'), ('comm_equipment', 'Communications Equipment'), ('comms_tower', 'Communication Tower'), ('camera', 'Surveillance Camera'), ('barrier', 'Barrier/Fencing')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('expected_lifespan_years', models.PositiveIntegerField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('non-operational', 'Non-operational')], default='good', max_length=20)),
                ('is_operational', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityForceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('transit', 'Transit Agent'), ('patrol', 'Patrol Officer'), ('intervention', 'Intervention Team Member'), ('special_intervention', 'Special Intervention Operator')], max_length=20)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('badge_number', models.CharField(max_length=50, unique=True)),
                ('is_armed', models.BooleanField(default=True)),
                ('years_of_service', models.PositiveIntegerField(default=0)),
                ('certifications', models.TextField(blank=True, help_text='Comma-separated list of certifications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('operational', 'Operational'), ('logistical', 'Logistical'), ('personnel', 'Personnel'), ('support', 'Support')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('floor_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ceiling_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of personnel', null=True)),
                ('has_backup_power', models.BooleanField(default=False)),
                ('has_environmental_control', models.BooleanField(default=False)),
                ('has_surveillance', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='scenarios.equipmentcategory')),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('personal', 'Personal Equipment'), ('protective', 'Protective Equipment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cost_range', models.CharField(blank=True, choices=[('budget', 'Budget'), ('mid', 'Mid-Range'), ('premium', 'Premium')], max_length=20)),
                ('protection_level', models.CharField(blank=True, choices=[('none', 'None'), ('basic', 'Basic'), ('level_ii', 'Level II'), ('level_iiia', 'Level IIIA'), ('level_iii', 'Level III'), ('level_iv', 'Level IV')], default='none', max_length=20)),
                ('maintenance_schedule', models.CharField(blank=True, help_text="e.g., 'Every 6 months'", max_length=100)),
                ('expected_lifespan_years', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (lethal, non-lethal, ballistic, etc.)', max_length=200)),
                ('is_restricted', models.BooleanField(default=False, help_text='Requires special authorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.equipmentcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_type', models.CharField(choices=[('lattice', 'Lattice Tower'), ('monopole', 'Monopole Tower'), ('guyed', 'Guyed Tower')], max_length=20)),
                ('height_meters', models.DecimalField(decimal_places=1, max_digits=6)),
                ('antenna_count', models.PositiveIntegerField(default=2)),
                ('transmission_power_watts', models.PositiveIntegerField(default=100)),
                ('coverage_range_km', models.DecimalField(decimal_places=1, max_digits=6)),
                ('has_encryption', models.BooleanField(default=True)),
                ('backup_power_hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fixed_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tower_specs', to='scenarios.fixedasset')),
            ],
            options={
                'verbose_name_plural': 'Communication Towers',
            },
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline'), ('hybrid', 'Hybrid')], max_length=20)),
                ('capacity_kw', models.PositiveIntegerField()),
                ('fuel_capacity_liters', models.PositiveIntegerField()),
                ('fuel_consumption_liters_per_hour', models.DecimalField(decimal_places=1, max_digits=5)),
                ('has_automatic_transfer_switch', models.BooleanField(default=True)),
                ('noise_level_db', models.PositiveIntegerField(blank=True, null=True)),
                ('fixed_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generator_specs', to='scenarios.fixedasset')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('structure_type', models.CharField(choices=[('toc', 'Tactical Operations Center'), ('station', 'Police/Security Station'), ('headquarters', 'Regional Headquarters'), ('barracks', 'Barracks/Base Housing'), ('armory', 'Armory/Weapons Facility'), ('training', 'Training Facility'), ('hangar', 'Hangar/Vehicle Maintenance'), ('detention', 'Detention Facility'), ('checkpoint', 'Checkpoint/Guard Post'), ('bunker', 'Fortified Bunker/Observation Post'), ('fob', 'Forward Operating Base'), ('medical', 'Medical Clinic/Hospital'), ('warehouse', 'Supply Warehouse'), ('maintenance', 'Maintenance & Repair Shop'), ('it_center', 'IT/Communications Center')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('construction_material', models.CharField(blank=True, max_length=100)),
                ('Floor_count', models.PositiveIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of personnel', null=True)),
                ('has_perimeter_fencing', models.BooleanField(default=True)),
                ('has_access_control', models.BooleanField(default=True)),
                ('has_backup_power', models.BooleanField(default=True)),
                ('has_communication_tower', models.BooleanField(default=False)),
                ('has_surveillance_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spaces', models.ManyToManyField(blank=True, related_name='structures', to='scenarios.space')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('infrastructure_type', models.CharField(choices=[('primary_road', 'Primary Roads/Access Routes'), ('secondary_road', 'Secondary Roads/Patrol Routes'), ('hlz', 'Heliport/HLZ'), ('rally_point', 'Rally Points'), ('perimeter_fence', 'Perimeter Fencing'), ('barriers', 'Vehicle Barriers/Obstacles'), ('checkpoint', 'Checkpoints/Guard Stations')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_structures', models.ManyToManyField(blank=True, related_name='connected_by_infrastructure', to='scenarios.structure')),
            ],
            options={
                'verbose_name_plural': 'Infrastructure',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='scenarios.structure'),
        ),
        migrations.CreateModel(
            name='SurveillanceCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(choices=[('ptz', 'Pan/Tilt/Zoom (PTZ)'), ('fixed_dome', 'Fixed Dome'), ('thermal', 'Thermal/FLIR'), ('hybrid', 'Hybrid Optical/Thermal')], max_length=20)),
                ('resolution', models.CharField(choices=[('1080p', '1080p Full HD'), ('2k', '2K'), ('4k', '4K UHD')], max_length=50)),
                ('viewing_angle_degrees', models.PositiveIntegerField()),
                ('night_vision_range_m', models.PositiveIntegerField(blank=True, null=True)),
                ('has_recording', models.BooleanField(default=True)),
                ('recording_storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_rate_fps', models.PositiveIntegerField(default=30)),
                ('fixed_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera_specs', to='scenarios.fixedasset')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit_type', models.CharField(choices=[('k9', 'K9 Unit'), ('sof', 'Special Operations Forces (SOF)'), ('binome', 'Two-man Patrol (Binome)')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='units', to='scenarios.securityforcemember')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_units', to='scenarios.securityforcemember')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SOFUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)])),
                ('specializations', models.CharField(blank=True, help_text='e.g., CQB, hostage rescue, counter-terrorism, dynamic entry', max_length=500)),
                ('training_level', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('elite', 'Elite')], default='advanced', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('team_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sof_leadership', to='scenarios.securityforcemember')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sof_unit', to='scenarios.unit')),
            ],
        ),
        migrations.CreateModel(
            name='K9Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canine_name', models.CharField(max_length=100)),
                ('canine_breed', models.CharField(choices=[('german_shepherd', 'German Shepherd'), ('belgian_malinois', 'Belgian Malinois'), ('labrador', 'Labrador Retriever'), ('other', 'Other')], max_length=20)),
                ('canine_age_years', models.DecimalField(decimal_places=1, max_digits=3)),
                ('specializations', models.CharField(help_text='Comma-separated specializations', max_length=200)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('work_hours_per_shift', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('rest_hours_required', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(24)])),
                ('is_active', models.BooleanField(default=True)),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k9_handler', to='scenarios.securityforcemember')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='k9_unit', to='scenarios.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('patrol_ground', 'Ground - Standard Patrol'), ('sru_ground', 'Ground - Special Response Unit (SRU)'), ('helicopter', 'Air - Rotary-wing (Helicopter)'), ('uav', 'Air - UAV (Drone)')], max_length=20)),
                ('registration', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('seating_capacity', models.PositiveIntegerField(default=2)),
                ('payload_capacity_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('max_speed_kmh', models.PositiveIntegerField(blank=True, null=True)),
                ('range_km', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('maintenance', 'In Maintenance')], default='good', max_length=20)),
                ('is_operational', models.BooleanField(default=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('odometer_km', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='scenarios.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_optical_camera', models.BooleanField(default=True)),
                ('has_thermal_camera', models.BooleanField(default=True)),
                ('has_obstacle_avoidance', models.BooleanField(default=True)),
                ('endurance_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('operational_altitude_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('max_range_km', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uav_specs', to='scenarios.vehicle')),
            ],
            options={
                'verbose_name_plural': 'UAVs',
            },
        ),
        migrations.CreateModel(
            name='Helicopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_hoist_system', models.BooleanField(default=True)),
                ('has_thermal_imaging', models.BooleanField(default=True)),
                ('has_door_guns', models.BooleanField(default=False)),
                ('has_rappel_system', models.BooleanField(default=True)),
                ('endurance_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('operational_ceiling_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_capacity_liters', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helicopter_specs', to='scenarios.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Helicopters',
            },
        ),
        migrations.CreateModel(
            name='ArmoredVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_rating', models.CharField(choices=[('b6', 'Level B6'), ('b7', 'Level B7')], max_length=10)),
                ('has_thermal_imaging', models.BooleanField(default=False)),
                ('has_nbc_filtration', models.BooleanField(default=False)),
                ('has_weapon_mounting', models.BooleanField(default=False)),
                ('fuel_capacity_liters', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='armored_specs', to='scenarios.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RoleEquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('transit', 'Transit Agent'), ('patrol', 'Patrol Officer'), ('intervention', 'Intervention Team Member'), ('special_intervention', 'Special Intervention Operator')], max_length=20)),
                ('requirement_level', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('prohibited', 'Prohibited')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.equipment')),
            ],
            options={
                'ordering': ['role', 'requirement_level'],
                'unique_together': {('role', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='MemberEquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('assignment_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='excellent', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.equipment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='scenarios.securityforcemember')),
            ],
            options={
                'ordering': ['-assignment_date'],
                'unique_together': {('member', 'equipment', 'is_active')},
            },
        ),
    ]
